FROM node:8

RUN npm install pm2 -g

WORKDIR .

COPY ./packages/common/package.json ./packages/common/package.json
COPY ./packages/text-miner/package.json ./packages/text-miner/package.json
COPY ./packages/neologisms/package.json ./packages/neologisms/package.json

RUN cd ./packages/neologisms && npm install --unsafe-perm && cd -

COPY . .

CMD ["pm2-docker", "ecosystem.config.js"]
