FROM node:8

RUN npm install pm2 -g
RUN npm install lerna -g
RUN npm install linklocal -g

WORKDIR /text-miner

COPY ./packages/common/package.json /text-miner/packages/common/package.json
COPY ./packages/rss-parser/package.json /text-miner/packages/rss-parser/package.json
COPY ./packages/text-miner/package.json /text-miner/packages/text-miner/package.json

RUN cd packages/text-miner && npm install && cd -

COPY . /text-miner

CMD ["pm2-docker", "ecosystem.config.js"]
