FROM node:8

RUN npm install pm2@latest -g

WORKDIR /neologisms

COPY ./packages/common/package.json /neologisms/packages/common/package.json
COPY ./packages/text-miner/package.json /neologisms/packages/text-miner/package.json

COPY ./packages/neologisms/package.json /neologisms/packages/neologisms/package.json

RUN cd packages/neologisms && npm install --unsafe-perm && cd -

COPY . /neologisms

CMD ["pm2-runtime", "ecosystem.config.js"]
