FROM node:8

RUN npm install pm2 -g
RUN npm install lerna -g
RUN npm install linklocal -g

WORKDIR /neologisms

COPY ./packages/common/package.json /neologisms/packages/common/package.json
COPY ./packages/text-miner/package.json /neologisms/packages/text-miner/package.json
COPY ./packages/neologisms/package.json /neologisms/packages/neologisms/package.json

RUN cd packages/neologisms && npm install && cd -

COPY . /neologisms

CMD ["pm2-docker", "ecosystem.config.js"]
