FROM node:8

RUN npm install pm2 -g
RUN npm install lerna -g
RUN npm install linklocal -g

WORKDIR /rss-parser

COPY ./packages/common/package.json /rss-parser/packages/common/package.json
COPY ./packages/rss-parser/package.json /rss-parser/packages/rss-parser/package.json
COPY ./packages/text-miner/package.json /rss-parser/packages/text-miner/package.json

RUN cd packages/rss-parser && npm install && cd -

COPY . /rss-parser

CMD ["pm2-docker", "ecosystem.config.js"]
