FROM node:8

RUN npm install pm2@latest -g

WORKDIR /rss-parser

COPY ./packages/common/package.json /rss-parser/packages/common/package.json
COPY ./packages/text-miner/package.json /rss-parser/packages/text-miner/package.json

COPY ./packages/rss-parser/package.json /rss-parser/packages/rss-parser/package.json

RUN cd packages/rss-parser && npm install --unsafe-perm && cd -

COPY . /rss-parser

CMD ["pm2-runtime", "ecosystem.config.js"]
